//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA_INTEGRAL_DUCON
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleado
    {
        public string Cedula { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Apellidos { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public int Dependencia { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaContratación { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Región { get; set; }
        public string País { get; set; }
        public string TelDomicilio { get; set; }
        public string Extensión { get; set; }
        public string Mail { get; set; }
        public bool Activo { get; set; }
        public string Zona { get; set; }
        public string Grupo { get; set; }
        public Nullable<bool> ReceptorObservaciones { get; set; }
    }
}
